Repository AY2223S1-CS2103T-W17-3/tp, pull requests merged in 2022-10, with the labels that each got.

#66 removed TA commands
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ta/AddTeachingAssistantCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ta/AddTeachingAssistantCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ta/TeachingAssistant.java
  src/main/java/seedu/address/model/ta/TeachingAssistantId.java
  src/main/java/seedu/address/model/ta/TeachingAssistantName.java
  src/main/java/seedu/address/model/ta/UniqueTeachingAssistantList.java
  src/main/java/seedu/address/model/ta/exceptions/DuplicateTeachingAssistantException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTeachingAssistant.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TeachingAssistantCard.java
  src/main/java/seedu/address/ui/TeachingAssistantListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TeachingAssistantListCard.fxml
  src/main/resources/view/TeachingAssistantListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/consultation/AddConsultationCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/AddReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorial/AddTutorialCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.Medium

#93 Student grade chart
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/student/ShowGradeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/GradeChart.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/GradeChart.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/consultation/AddConsultationCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/AddReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/student/ShowGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorial/AddTutorialCommandTest.java
Labels: priority.Medium

#99 Update DG for show grade
  docs/DeveloperGuide.md
  docs/diagrams/ShowGradeSequenceDiagram.puml
  docs/images/ShowGradeSequenceDiagram.png
Labels: priority.Low, type.Documentation

#98 Update user stories
  README.md
  docs/DeveloperGuide.md
Labels: priority.Low, type.Documentation

#95 Minor fixes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/student/AddCommand.java
  src/main/java/seedu/address/logic/commands/student/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/student/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/student/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/student/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/student/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/student/EditStudentDescriptorTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Bug, type.Documentation

#100 Mark unmark reminder commands
  src/main/java/seedu/address/logic/commands/reminder/MarkReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/UnmarkReminderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/reminder/MarkReminderCommandParser.java
  src/main/java/seedu/address/logic/parser/reminder/UnmarkReminderCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderStatus.java
  src/main/java/seedu/address/model/reminder/UniqueReminderList.java
  src/main/java/seedu/address/storage/JsonAdaptedReminder.java
  src/main/java/seedu/address/ui/ReminderCard.java
  src/test/java/seedu/address/logic/commands/consultation/AddConsultationCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/AddReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/student/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorial/AddTutorialCommandTest.java
Labels: priority.Medium

#97 Add priority to reminders
  src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/reminder/AddReminderCommandParser.java
  src/main/java/seedu/address/logic/parser/reminder/ReminderParserUtil.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderDeadline.java
  src/main/java/seedu/address/model/reminder/ReminderName.java
  src/main/java/seedu/address/model/reminder/ReminderPriority.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedReminder.java
  src/main/java/seedu/address/ui/ReminderCard.java
  src/main/resources/view/ReminderListCard.fxml
  src/test/java/seedu/address/testutil/ReminderBuilder.java
Labels: priority.Medium

#112 Update V1.3 user guide
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#111 Update gui
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/ReminderCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/ReminderListCard.fxml
Labels: type.Enhancement

#105 Generic clear command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/consultation/ConsultationParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/consultation/AddConsultationCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/AddReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/student/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/student/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorial/AddTutorialCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#115 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#114 Add icons
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/images/correct.png
  src/main/resources/images/email.png
  src/main/resources/images/grade.png
  src/main/resources/images/phone.png
  src/main/resources/images/student-card.png
  src/main/resources/images/telegram.png
  src/main/resources/images/test.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement

#118 Sort reminders priority
  src/main/java/seedu/address/logic/commands/reminder/SortReminderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderPriority.java
  src/main/java/seedu/address/model/reminder/UniqueReminderList.java
  src/test/java/seedu/address/logic/commands/consultation/AddConsultationCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/AddReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/SortReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/student/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorial/AddTutorialCommandTest.java
Labels: priority.Medium

#110 Add missing reminder test cases
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/reminder/DeleteReminderCommandTest.java
  src/test/java/seedu/address/testutil/TypicalReminders.java
  src/test/java/seedu/address/testutil/TypicalTutorials.java
Labels: priority.Low

#120 Sort reminders deadline
  src/main/java/seedu/address/logic/commands/reminder/SortReminderByDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/reminder/SortReminderByPriorityCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/datetime/Datetime.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderDeadlineComparator.java
  src/main/java/seedu/address/model/reminder/ReminderPriorityComparator.java
  src/main/java/seedu/address/model/reminder/UniqueReminderList.java
  src/test/java/seedu/address/logic/commands/consultation/AddConsultationCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/AddReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/SortReminderByDeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/SortReminderByPriorityCommandTest.java
  src/test/java/seedu/address/logic/commands/student/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorial/AddTutorialCommandTest.java
Labels: priority.Medium

#119 Add switch command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/commands/consultation/AddConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/DeleteConsultationCommand.java
  src/main/java/seedu/address/logic/commands/student/AddCommand.java
  src/main/java/seedu/address/logic/commands/student/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/student/EditCommand.java
  src/main/java/seedu/address/logic/commands/student/FindCommand.java
  src/main/java/seedu/address/logic/commands/student/ShowGradeCommand.java
  src/main/java/seedu/address/logic/commands/tutorial/AddTutorialCommand.java
  src/main/java/seedu/address/logic/commands/tutorial/DeleteTutorialCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SwitchCommandParser.java
  src/main/java/seedu/address/model/ModelType.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/student/ShowGradeCommandTest.java
Labels: type.Enhancement

#121 Edit reminder status
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/reminder/MarkReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/UnmarkReminderCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderDescription.java
  src/main/java/seedu/address/model/reminder/ReminderStatus.java
  src/main/java/seedu/address/storage/JsonAdaptedReminder.java
  src/main/java/seedu/address/ui/ReminderCard.java
Labels: priority.Low

#126 Implemented a ComplexReminderComparator
  src/main/java/seedu/address/logic/commands/reminder/EditReminderCommand.java
  src/main/java/seedu/address/model/reminder/ReminderComplexComparator.java
  src/main/java/seedu/address/model/reminder/ReminderDeadlineComparator.java
  src/main/java/seedu/address/model/reminder/ReminderPriorityComparator.java
  src/main/java/seedu/address/model/reminder/UniqueReminderList.java
Labels: priority.Medium

#131 Update ug
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.Documentation

#136 V1.3 user guide
  docs/UserGuide.md
Labels: type.Documentation

#195 Update UG to reflect prefix with multiple definitions
  docs/UserGuide.md
Labels: type.Documentation

#196 Reminder test cases
  docs/UserGuide.md
  src/main/java/seedu/address/model/student/StudentId.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/reminder/EditReminderCommandTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditReminderDescriptorBuilder.java
Labels: type.Documentation, Add test case

#201 Edit PPP for yeoyujie
  docs/team/yeoyujie.md
Labels: type.Documentation

#202 Fix reminder status changing when edit and update reminder test cases
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/EditReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/SortReminderCommand.java
  src/main/java/seedu/address/logic/parser/reminder/AddReminderCommandParser.java
  src/main/java/seedu/address/logic/parser/reminder/SortReminderCommandParser.java
  src/main/java/seedu/address/model/reminder/UniqueReminderList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/reminder/MarkReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/SortReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/UnmarkReminderCommandTest.java
  src/test/java/seedu/address/logic/parser/AddReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/consultation/AddConsultationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/reminder/AddReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/reminder/DeleteReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/reminder/EditReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/reminder/MarkReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/reminder/ReminderParserUtilTest.java
  src/test/java/seedu/address/logic/parser/reminder/SortReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/reminder/UnmarkReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/student/AddStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/student/DeleteStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/student/EditStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/student/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/tutorial/DeleteTutorialCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalReminders.java
Labels: type.Bug, priority.High, Add test case
