Repository AY2223S1-CS2103T-W17-3/tp, pull requests merged in 2022-11, with the labels that each got.

#198 Branch fix tutorial
  src/main/java/seedu/address/logic/commands/tutorial/AddTutorialCommand.java
  src/main/java/seedu/address/logic/commands/tutorial/EditTutorialCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/datetime/WeeklyTimeslot.java
  src/main/java/seedu/address/model/tutorial/Tutorial.java
  src/main/java/seedu/address/model/tutorial/UniqueTutorialList.java
  src/test/java/seedu/address/logic/commands/consultation/AddConsultationCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/AddReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/student/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorial/AddTutorialCommandTest.java
  src/test/java/seedu/address/model/datetime/WeeklyTimeslotTest.java
Labels: type.Bug

#211 V1.4 docs update
  docs/UserGuide.md
  docs/team/yeoyujie.md
  src/main/java/seedu/address/logic/commands/reminder/SortReminderCommand.java
Labels: type.Documentation

#205 Fix student bugs
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/consultation/EditConsultationCommand.java
  src/main/java/seedu/address/logic/commands/reminder/EditReminderCommand.java
  src/main/java/seedu/address/logic/commands/student/EditStudentCommand.java
  src/main/java/seedu/address/logic/commands/tutorial/EditTutorialCommand.java
  src/main/java/seedu/address/logic/parser/student/StudentParserUtil.java
  src/main/java/seedu/address/model/student/Attendance.java
  src/main/java/seedu/address/model/student/Grade.java
  src/main/java/seedu/address/model/student/Participation.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/test/java/seedu/address/logic/commands/reminder/EditReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/student/EditStudentCommandTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug

#215 Parse time after now
  src/main/java/seedu/address/model/datetime/DatetimeCommonUtils.java
  src/main/java/seedu/address/model/datetime/DatetimeRange.java
  src/main/java/seedu/address/model/datetime/WeeklyTimeslot.java
  src/main/java/seedu/address/model/reminder/ReminderDeadline.java
  src/main/java/seedu/address/model/reminder/ReminderDeadlineComparator.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/reminder/MarkReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/UnmarkReminderCommandTest.java
  src/test/java/seedu/address/logic/parser/consultation/AddConsultationCommandParserTest.java
  src/test/java/seedu/address/model/datetime/DatetimeCommonUtilsTest.java
  src/test/java/seedu/address/model/datetime/DatetimeRangeTest.java
  src/test/java/seedu/address/model/datetime/DatetimeTest.java
  src/test/java/seedu/address/model/datetime/WeeklyTimeslotTest.java
  src/test/java/seedu/address/testutil/ReminderBuilder.java
Labels: type.Bug

#216 Update the definition of same reminders.
  docs/UserGuide.md
  src/main/java/seedu/address/model/datetime/DatetimeCommonUtils.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/UniqueReminderList.java
Labels: type.Bug, type.Documentation

#220 Edit UG find command
  docs/UserGuide.md
Labels: type.Documentation

#226 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#227 fixed grade bug
  src/main/java/seedu/address/model/student/Grade.java
  src/main/java/seedu/address/model/student/TelegramHandle.java
Labels: type.Bug

#228 Student test case
  src/main/java/seedu/address/model/student/Grade.java
  src/test/java/seedu/address/model/student/AttendanceTest.java
  src/test/java/seedu/address/model/student/GradeTest.java
  src/test/java/seedu/address/model/student/ParticipationTest.java
  src/test/java/seedu/address/model/student/StudentIdTest.java
  src/test/java/seedu/address/model/student/TelegramTest.java
Labels: Add test case

#230 minor updates to ug
  docs/UserGuide.md
Labels: type.Documentation

#234 Remove local date time
  docs/UserGuide.md
  src/main/java/seedu/address/model/datetime/DatetimeCommonUtils.java
  src/main/java/seedu/address/model/datetime/DatetimeRange.java
  src/test/java/seedu/address/model/datetime/DatetimeCommonUtilsTest.java
Labels: type.Documentation

#238 Edit consultation test cases
  src/main/java/seedu/address/model/student/Grade.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/consultation/EditConsultDescriptorTest.java
  src/test/java/seedu/address/logic/commands/consultation/EditConsultationCommandTest.java
  src/test/java/seedu/address/logic/commands/student/EditStudentCommandTest.java
  src/test/java/seedu/address/testutil/EditConsultationDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalConsultations.java
Labels: Add test case

#229 New test cases
  src/test/java/seedu/address/model/commons/ModuleTest.java
  src/test/java/seedu/address/model/commons/VenueTest.java
  src/test/java/seedu/address/model/tutorial/TutorialNameTest.java
Labels: Add test case

#247 Update UG section
  docs/UserGuide.md
Labels: type.Documentation

#249 add more pictures
  docs/UserGuide.md
  docs/images/AddStudent.png
  docs/images/AnnotatedStudent.png
  docs/images/AnnotatedUi.png
  docs/images/EditStudent.png
  docs/images/ExtractEmails1.png
  docs/images/FindStudent.png
  docs/images/Student.png
  docs/images/Ui.png
Labels: type.Documentation

#253 all tutorial and consultation images
  docs/UserGuide.md
  docs/images/AddConsultation.png
  docs/images/AddTutorial.png
  docs/images/AnnotatedConsultation.png
  docs/images/AnnotatedTutorial.png
  docs/images/Consultation.png
  docs/images/EditConsultation.png
  docs/images/EditTutorial.png
  docs/images/Tutorial.png
Labels: type.Documentation

#254 Add manual testing for tutorial
  docs/DeveloperGuide.md
Labels: type.Documentation

#258 reminder images and extract email
  docs/UserGuide.md
  docs/images/AddReminder.png
  docs/images/AnnotatedReminder.png
  docs/images/EditReminder.png
  docs/images/ExtractEmails2.png
  docs/images/ExtractEmails3.png
  docs/images/ExtractEmails4.png
  docs/images/MarkedReminder.png
  docs/images/Reminder.png
  docs/images/ReminderDeadline.png
Labels: type.Documentation

#262 Remove all method checking module and tutorial for student and consultation
  src/main/java/seedu/modquik/logic/commands/consultation/AddConsultationCommand.java
  src/main/java/seedu/modquik/logic/commands/consultation/EditConsultationCommand.java
  src/main/java/seedu/modquik/logic/commands/student/AddStudentCommand.java
  src/main/java/seedu/modquik/logic/commands/student/EditStudentCommand.java
  src/main/java/seedu/modquik/model/Model.java
  src/main/java/seedu/modquik/model/ModelManager.java
  src/main/java/seedu/modquik/model/util/SampleDataUtil.java
  src/test/java/seedu/modquik/logic/LogicManagerTest.java
  src/test/java/seedu/modquik/logic/commands/consultation/AddConsultationCommandTest.java
  src/test/java/seedu/modquik/logic/commands/consultation/EditConsultationCommandTest.java
  src/test/java/seedu/modquik/logic/commands/reminder/AddReminderCommandTest.java
  src/test/java/seedu/modquik/logic/commands/student/AddStudentCommandTest.java
  src/test/java/seedu/modquik/logic/commands/student/EditStudentCommandTest.java
  src/test/java/seedu/modquik/logic/commands/tutorial/AddTutorialCommandTest.java
  src/test/java/seedu/modquik/testutil/TypicalConsultations.java
  src/test/java/seedu/modquik/testutil/TypicalPersons.java
Labels: type.Bug

#260 Update Ui class diagram
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Documentation

#268 Add manual testing for switch tabs
  docs/DeveloperGuide.md
Labels: type.Documentation

#272 Update UG: switch command
  docs/UserGuide.md
Labels: type.Documentation

#275 Handle data file in wrong format
  src/main/java/seedu/modquik/storage/JsonSerializableModQuik.java
Labels: type.Bug

#274 Add Use Cases for DG
  docs/DeveloperGuide.md
  docs/team/yeoyujie.md
  src/main/java/seedu/modquik/model/consultation/ConsultationDescription.java
  src/main/java/seedu/modquik/model/reminder/ReminderDescription.java
Labels: type.Documentation

#263 Add manual testing for consultation
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/modquik/model/consultation/ConsultationDescription.java
  src/main/java/seedu/modquik/model/consultation/ConsultationName.java
Labels: type.Documentation

#278 Add more tests
  src/test/java/seedu/modquik/logic/commands/SwitchCommandTest.java
  src/test/java/seedu/modquik/model/tutorial/UniqueTutorialListTest.java
  src/test/java/seedu/modquik/storage/JsonAdaptedTutorialTest.java
  src/test/java/seedu/modquik/testutil/TutorialBuilder.java
  src/test/java/seedu/modquik/testutil/TypicalTutorials.java
Labels: Add test case

#277 Edit dg
  docs/DeveloperGuide.md
  docs/team/yeoyujie.md
Labels: type.Documentation

#279 Update architecture diagram
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: type.Documentation

#281 Update more details in UG
  docs/UserGuide.md
Labels: type.Documentation

#287 Update ppp-lilythchu
  docs/AboutUs.md
  docs/team/lilythchu.md
Labels: type.Documentation

#288 Model Diagram
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Documentation

#289 Student manual testing
  docs/DeveloperGuide.md
Labels: type.Documentation

#291 formatting of dg
  docs/DeveloperGuide.md
  docs/diagrams/AddStudentSequenceDiagram.puml
  docs/images/AddStudentSequenceDiagram.png
Labels: type.Documentation

#292 DG update diagrams
  docs/DeveloperGuide.md
  docs/diagrams/DeleteStudentActivityDiagram.puml
  docs/images/DeleteStudentActivityDiagram.png
  docs/images/SortReminderSequenceDiagram.png
  docs/images/johndoe.png
Labels: type.Documentation

#300 PPP-Anh
  docs/team/april-anh.md
Labels: type.Documentation

#320 minor fixes
  docs/UserGuide.md
  docs/images/FindStudent.png
Labels: type.Documentation
